CREATE TABLE IF NOT EXISTS rest_emp (
	id INT AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	phone VARCHAR(255) NOT NULL,
	address VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=INNODB;